# Generated by Django 5.1.2 on 2025-01-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_messagesending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=15)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_email', models.CharField(max_length=120)),
                ('c_password', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='messagesending',
            name='status',
        ),
    ]
