# Generated by Django 5.1.2 on 2025-01-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_register_remove_messagesending_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registration',
        ),
    ]
