# Generated by Django 5.1.2 on 2025-01-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_ambulancebooking_amount_ambulancebooking_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancebooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ambulancebooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ambulancebooking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='ambulancebooking',
            name='user',
        ),
    ]
